CREATE TABLE user(
  id INTEGER AUTOINCREMENT,
  email TEXT NOT NUL,
  password TEXT NOT NUL,
  PRIMARY KEY(id)
);

CREATE TABLE cloudset(
  id INTEGER AUTOINCREMENT,
  userId INTEGER,
  name TEXT NOT NUL,
  PRIMARY KEY(id),
  FOREIGN KEY(userId) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE file(
  id INTEGER AUTOINCREMENT,
  userId INTEGER,
  name TEXT NOT NUL,
  PRIMARY KEY(id),
  FOREIGN KEY(userId) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE cloudsetMapFile(
  id INTEGER AUTOINCREMENT,
  cloudsetId INTEGER,
  fileId INTEGER,
  PRIMARY KEY(id),
  FOREIGN KEY(cloudsetId) REFERENCES cloudset(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(fileId) REFERENCES file(id) ON UPDATE CASCADE ON DELETE CASCADE 
);